# Generated by Django 6.0.2 on 2026-03-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes')], max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Media/Images')),
                ('pdfs', models.FileField(blank=True, null=True, upload_to='Media/pdfs')),
            ],
        ),
    ]
